/**
 * src/pages/robots.txt.ts
 *
 * Astro endpoint that generates robots.txt at build time.
 * Served as /robots.txt — no static file needed in public/.
 *
 * Rules:
 *   - All crawlers: allow everything except the /og/ directory.
 *     OG images are large PNG files that add no value to search indexes
 *     and can inflate crawl budget on low-traffic sites.
 *   - GPTBot and Claude-Web: explicitly allowed. These bots do not
 *     negatively affect academic discoverability and may surface the
 *     H-Bar article to researchers using AI-assisted literature tools.
 *   - Sitemap declaration: points to the Astro-generated sitemap index.
 *
 * Cloudflare Pages note:
 *   @astrojs/sitemap generates sitemap-index.xml and sitemap-0.xml
 *   in the dist/ root. The Sitemap directive below uses the absolute
 *   URL form required by Google Search Console.
 */

import type { APIRoute } from 'astro';

export const GET: APIRoute = ({ site }) => {
  const siteURL = site ?? 'https://bamsyar.com';

  const content = `# robots.txt — bamsyar.com
# Generated by Astro at build time

User-agent: *
Allow: /
Disallow: /og/

# Sitemap
Sitemap: ${siteURL}sitemap-index.xml
`;

  return new Response(content, {
    headers: {
      'Content-Type': 'text/plain; charset=utf-8',
    },
  });
};
